#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#BASC_CONFIG FILE


instance:
    proc_mem: [3,6]
<<<<<<< HEAD
    roi_mask_file: '/Users/aki.nikolaidis/MNI152_T1_2mm_brainmask.nii.gz'
    roi2_mask_file: '/Users/aki.nikolaidis/MNI152_T1_2mm_brainmask.nii.gz'
    #roi_mask_file: '/Users/aki.nikolaidis/Downloads/MNI152_T1_3mm_brain.nii.gz'
=======
    #roi_mask_file: '/Users/aki.nikolaidis/Google Drive/DropboxArchive/UIUC_Projects/FYP/MNI152_T1_2mm_brain.nii.gz'
    roi_mask_file: '/Users/aki.nikolaidis/Downloads/MNI152_T1_3mm_brain.nii.gz'
>>>>>>> master
    dataset_bootstraps: 5
    timeseries_bootstraps: 5
    n_clusters: 400
    output_size: 5000
    bootstrap_list: list(range(0,dataset_bootstraps))
<<<<<<< HEAD
    cross_cluster: True
    affinity_threshold: [0.8, 0.8]#, 0.8, 0.8]
    out_dir: '/Users/aki.nikolaidis/Desktop/PyTest'
=======
    cross_cluster: False
    affinity_threshold: [0.8, 0.8, 0.8, 0.8]
    out_dir: '/Users/aki.nikolaidis/PyNetsTest'
>>>>>>> master
    run: True

    
   
    
<<<<<<< HEAD
#runfile('/Users/aki.nikolaidis/git_repo/ALL_PYNETS/PyNets/pynets/pynets_run.py',args="-i '/Users/aki.nikolaidis/git_repo/ALL_PYNETS/PyNets_NHW1/Sublist.txt' -basc 'True' -pm '2,4', -dt '0.3' -ns '4' -model 'sps'", wdir='/Users/aki.nikolaidis/git_repo/ALL_PYNETS')
=======
    
>>>>>>> master
